livereload: true
timezone: America/New_York

title: Ktt Development Wiki

plugins:
  - jekyll-readme-index
  - jekyll-optional-front-matter

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
exclude:
  - "CNAME"
  - "LICENSE"
  - ".gitignore"
