livereload: true
timezone: America/New_York

title: Ktt Development Wiki
url: https://docs.kttdevelopment.com/

plugins:
  - jekyll-readme-index
  - jekyll-optional-front-matter

sass:
  sass_dir: /dependencies/kttdevelopment/css
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - "CNAME"
  - "LICENSE"
  - ".gitignore"

compress_html:
  clippings: []
  comments: all
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []