livereload: true
timezone: America/New_York

title: Ktt Development Wiki

plugins:
  - jekyll-readme-index
  - jekyll-optional-front-matter

sass:
  sass_dir: /dependencies/kttdevelopment/css
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
exclude:
  - "CNAME"
  - "LICENSE"
  - ".gitignore"
