livereload: true

title: Ktt Development Wiki

defaults:
  - scope:
      path: "*.md"
    values:
      layout: "wiki"
  - scope:
      path: "*.html"
    values:
      layout: "default"
exclude:
  - "*."
  - "*.bat"
